import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * RegistryCertificateService
 * 
 * Handles generation of official verification certificates in PDF format.
 */
class RegistryCertificateService {
    /**
     * Generate a Verification Certificate for a provider
     */
    async generateCertificate(provider) {
        const doc = new jsPDF();
        
        // Add Header
        doc.setFillColor(0, 86, 179); // Primary Blue
        doc.rect(0, 0, 210, 40, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text('REPUBLIC OF SOUTH AFRICA', 105, 15, { align: 'center' });
        doc.setFontSize(14);
        doc.text('NATIONAL REGISTRY SENTINEL SYSTEM', 105, 25, { align: 'center' });
        doc.setFontSize(10);
        doc.text('OFFICIAL VERIFICATION CERTIFICATE', 105, 33, { align: 'center' });

        // Add Logo Circle Placeholder
        doc.setDrawColor(255, 255, 255);
        doc.setLineWidth(1);
        doc.circle(20, 20, 10, 'S');

        // Certificate Body
        doc.setTextColor(30, 41, 59);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Generated on: ${new Date().toLocaleString('en-ZA')}`, 15, 50);
        doc.text(`Reference ID: ZA-${Math.random().toString(36).substring(2, 10).toUpperCase()}-V4`, 15, 55);

        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text('VERIFICATION STATEMENT', 105, 75, { align: 'center' });

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text('This serves to officially validate the registration status of:', 105, 85, { align: 'center' });

        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 86, 179);
        doc.text(provider.name.toUpperCase(), 105, 105, { align: 'center' });

        // Table of details
        const details = [
            ['Registration Number', provider.reg || provider.registration_number || 'N/A'],
            ['Category', provider.category || 'N/A'],
            ['Authority', provider.body || provider.authority || 'N/A'],
            ['Status', provider.status || 'N/A'],
            ['Verification Level', 'Sovereign Sentinel V4.0'],
            ['Integrity Hash', provider.blockchain_hash || 'SHA256:8E94...F4B2']
        ];

        doc.autoTable({
            startY: 120,
            head: [['Attribute', 'Verified Value']],
            body: details,
            theme: 'grid',
            headStyles: { fillColor: [0, 86, 179] },
            styles: { fontSize: 11, cellPadding: 5 }
        });

        // Add Warning if any
        if (provider.warning || provider.status === 'Deregistered') {
            const finalY = doc.lastAutoTable.finalY + 15;
            doc.setFillColor(254, 242, 242);
            doc.rect(15, finalY, 180, 20, 'F');
            doc.setDrawColor(220, 38, 38);
            doc.rect(15, finalY, 180, 20, 'S');
            doc.setTextColor(220, 38, 38);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('⚠️ SECURITY WARNING', 20, finalY + 8);
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.text(provider.warning || 'Alert: Recently deregistered or non-compliant.', 20, finalY + 15);
        }

        // Footer
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text('This document was generated by the Sumbandila Sentinel AI Platform.', 105, pageHeight - 20, { align: 'center' });
        doc.text('Validity can be confirmed by scanning the original QR code via the official mobile application.', 105, pageHeight - 15, { align: 'center' });

        // Save
        doc.save(`Sumbandila_Verification_${provider.name.replace(/\s+/g, '_')}.pdf`);
        return true;
    }
}

export const RegistryCertService = new RegistryCertificateService();
