import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

class KirovAnalyticsHub:
    """
    Kirov Dynamics Analytics Hub (v1.0)
    Generates strategic insights and data visualizations for the Sumbandila Platform.
    """
    def __init__(self, data_path=None):
        self.data_path = data_path
        self.df = None

    def generate_mock_data(self, samples=1000):
        """Generates high-fidelity mock registry data for analysis."""
        np.random.seed(42)
        data = {
            'institution_id': [f'INS-{i:04d}' for i in range(samples)],
            'province': np.random.choice(['Gauteng', 'Western Cape', 'KZN', 'Limpopo', 'Free State'], samples),
            'age_years': np.random.normal(12, 5, samples).clip(1, 40),
            'verification_status': np.random.choice(['Verified', 'Pending', 'Flagged'], samples, p=[0.7, 0.2, 0.1]),
            'trust_score': np.random.uniform(30, 100, samples),
            'monthly_verifications': np.random.poisson(150, samples)
        }
        self.df = pd.DataFrame(data)
        return self.df

    def get_provincial_insights(self):
        """Aggregates trust scores by province."""
        if self.df is None: self.generate_mock_data()
        
        summary = self.df.groupby('province').agg({
            'trust_score': 'mean',
            'monthly_verifications': 'sum',
            'institution_id': 'count'
        }).rename(columns={'institution_id': 'total_entities'})
        
        return summary.sort_values(by='trust_score', ascending=False)

    def export_report(self, output_path='docs/analytics_report.md'):
        """Exports a Markdown report with data tables."""
        summary = self.get_provincial_insights()
        
        report = "# 📊 Kirov Dynamics: Sumbandila Regional Analytics\n\n"
        report += "Strategic data analysis for the pan-African digital trust layer.\n\n"
        report += "## Provincial Trust Distribution\n\n"
        report += summary.to_markdown()
        report += "\n\n---\n*Report generated by Kirov Analytics Engine v1.0*"
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(report)
        print(f"Report exported to {output_path}")

if __name__ == "__main__":
    hub = KirovAnalyticsHub()
    hub.export_report()
